# Generated by Django 2.0.2 on 2018-02-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostsoul_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='content',
        ),
    ]
